export PGUSER=postgres
psql <<- EOSQL
    CREATE USER ${POSTGRES_CUSTOM_USER} WITH UNENCRYPTED PASSWORD '${POSTGRES_CUSTOM_PASSWORD}';
    CREATE DATABASE ${POSTGRES_CUSTOM_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_CUSTOM_DATABASE} TO ${POSTGRES_CUSTOM_USER};
EOSQL
